services:
  mysql-bitcoin:
    image: renatohvo/mysql-quarkus-db:8.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${DB_ROOT_PASSWORD}
    command:
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/bitcoin-script.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./bitcoin-script.sql:/docker-entrypoint-initdb.d/bitcoin-script.sql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'
          memory: 768M
        reservations:
          cpus: '0.25'
          memory: 384M
    ports:
      - 3306:3306
    networks:
      - metrics

  bitcoin-jvm:
    image: renatohvo/bitcoin-quarkus-jvm:v1.1
    environment:
      QUARKUS_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-bitcoin:3306/bitcoin?autoReconnect=true
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.4'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    networks:
      - metrics

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.15'
          memory: 128M
        reservations:
          cpus: '0.05'
          memory: 64M
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - metrics

  prometheus:
    image: prom/prometheus:v2.26.0
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.15'
          memory: 128M
    networks:
      - metrics
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      # resources:
      #   limits:
      #     cpus: '0.5'
      #     memory: 256M
      #   reservations:
      #     cpus: '0.25'
      #     memory: 128M
    networks:
      - metrics
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 192M
        reservations:
          cpus: '0.1'
          memory: 96M
    networks:
      - metrics

  promtail:
    image: grafana/promtail
    command:
      --config.file=/etc/promtail/promtail.yml
    volumes:
      - caddy_logs:/var/log/caddy
      - promtail_positions:/run/promtail
      - /var/log:/var/log
      - ./config/promtail.yml:/etc/promtail/promtail.yml
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.1'
          memory: 96M
        reservations:
          cpus: '0.05'
          memory: 48M
    networks:
      - metrics

  portainer:
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      mode: global  # 1 instância por nó
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    networks:
      - metrics

  crowdsec:
    image: crowdsecurity/crowdsec:latest
    command: sh /crowdsec-setup.sh
    environment:
      - GID=1000
      - BOUNCER_KEY_CADDY=${CROWDSEC_CADDY_BOUNCER_API_KEY}
    volumes:
      - ./config/crowdsec-setup.sh:/crowdsec-setup.sh
      - ./config/acquis.yaml:/etc/crowdsec/acquis.yaml:ro
      # - ./config/mywhitelist.yaml:/etc/crowdsec/parsers/s02-enrich/mywhitelist.yaml:ro
      - crowdsec_config:/etc/crowdsec
      - crowdsec_data:/var/lib/crowdsec/data
      - crowdsec_db:/var/lib/crowdsec/db
      - caddy_logs:/var/log/caddy
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.2'
          memory: 192M
        reservations:
          cpus: '0.1'
          memory: 96M
    ports:
      - 8080:8080
    networks:
      - metrics

  caddy:
    image: renatohvo/caddy-crowdsec-duckdns:latest
    environment:
      CROWDSEC_API_KEY: ${CROWDSEC_CADDY_BOUNCER_API_KEY}
      CROWDSEC_AGENT_HOST: http://crowdsec:8080
    configs:
      - source: caddyfile
        target: /etc/caddy/Caddyfile
        uid: '1000'
        gid: '1000'
        mode: 0400   # Somente leitura para o dono
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      resources:
        limits:
          cpus: '0.2'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
    volumes:
      - caddy_site:/srv
      - caddy_data:/data
      - caddy_config:/config
      - caddy_logs:/var/log/caddy
    ports:
      - mode: host
        published: 80
        target: 80
      - mode: host
        published: 443
        target: 443
    networks:
      - metrics

  kuma:
    image: louislam/uptime-kuma:latest
    environment:
      - TZ=America/Sao_Paulo
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
      # resources:
      #   limits:
      #     cpus: '0.2'
      #     memory: 128M
      #   reservations:
      #     cpus: '0.1'
      #     memory: 64M
    volumes:
      - kuma_data:/app/data
    networks:
      - metrics

  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - APP_URL=https://meusite.duckdns.org/
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - heimdall_config:/config
    networks:
      - metrics

configs:
  caddyfile:
    file: ./caddy/Caddyfile
    # external: true  # docker config create caddyfile ./caddy/Caddyfile

networks:
  metrics:
    driver: overlay

volumes:
  mysql_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  portainer_data:
    driver: local
  caddy_site:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  caddy_logs:
    driver: local
  crowdsec_config:
    driver: local
  crowdsec_data:
    driver: local
  crowdsec_db:
    driver: local
  kuma_data:
    driver: local
  promtail_positions:
    driver: local
  heimdall_config:
    driver: local
