global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'bitcoin-jvm'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['bitcoin-jvm:8081']
  - job_name: 'crowdsec-firewall-bouncer'
    static_configs:
      - targets: ['172.17.0.1:60601']
